# Configure regular AutoRecon options at the top of this file.

verbose = 1
only-scans-dir = true
no-port-dirs = true


# Configure global options here.
[global]
username-wordlist = '/usr/share/wordlists/seclists/Usernames/cirt-default-usernames.txt'
password-wordlist = '/usr/share/wordlists/seclists/Passwords/xato-net-10-million-passwords-100.txt'

# Configure plugin options here.
[onesixtyone]
community-strings = '/usr/share/wordlists/seclists/Discovery/SNMP/snmp-onesixtyone.txt'

[dirbuster]
wordlist = ['/usr/share/seclists/Discovery/Web-Content/combined_words.txt', '/usr/share/seclists/Discovery/Web-Content/api-endpoints-res.txt', '/usr/share/seclists/Discovery/Web-Content/combined_directories.txt']
